Review
BurovYA/ono-tebe-nado pull request #1
Opened 2024-08-06 17:54 UTC by BurovYA

2024-08-06 19:47 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Здравствуйте!  У вас получилась хорошая работа!

_Что понравилось:_

- Хорошая структура HTML
- похоже на макет
- нет скролла от 1100px и более и все элементы отображаются корректно
- Хорошее форматирование документа
- хорошие стили
- используется семантика
- Используются списки


_Что необходимо исправить:_

- **Все комментарии, кроме комментариев с пометками «Можно лучше» и «Отлично». А так же не забудьте проверить, есть ли свёрнутые комментарии, которые обычно находятся по центру страницы с ревью при прокрутке вниз, и выглядят следующим образом https://disk.yandex.ru/i/FyX-8tzeqLjimw**

- `1, 2, first, second и т.д`  порядковые числительные не следует применять  в названиях, т.к. порядок или числовое значение может измениться. **Нужно переименовать все подобные классы** 


- Несоответствия макету:
    - https://disk.yandex.ru/i/1Y-eGAACn4s-zA отступ между колонок




_Что можно улучшить:_

- Все комментарии "Можно лучше"

- Селекторы в файле стилей должны располагаться в порядке их появления в html

- В любом месте в файлах CSS в проекте(кроме самого CSS файла подключения шрифтов, где указывается только название подключаемого шрифта), где указано свойство  `font-family`  помимо основного шрифта так же должен быть указан альтернативный шрифт и тип засечек. Это делается для того, что если по каким-то причинами основной шрифт не загрузится, то внешний вид страницы не будет изменен очень сильно.  Порядок написания шрифтов: Основной шрифт, [Веб-безопасный альтернативный шрифт(по ссылке список этих шрифтов)](https://www.cssfontstack.com/), Тип засечек. Пример ` font-family: Inter, Arial, sans-serif; ` 

- Желательно использовать все классы по БЭМ. 
  - https://ru.bem.info/methodology/quick-start/
  - Проверить ошибки БЭМ можно на  https://nglazov.github.io/bem-validator-page/
  - струтуру можно проверить на https://yoksel.github.io/html-tree/

- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того чтобы пользователю не приходилось заново открывать сайт проекта
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 


**Напоминание:** После выполнения всех критических замечаний работа будет принята. Предложения по улучшению выполняются по желанию.

Желаю успеха!

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +              src="./images/yt.svg"
Не та картинка и не тот альт

2024-08-06 19:47 UTC, Avaakum commented on styles/style.css
> +  top: 0;
---

**Можно лучше:**


Или вместо координат в данном случае можно использовать свойство  ` inset: 0; `, так как отступы от всех краёв родительского элемента нулевые

Примеры и варианты значений этого свойства можно посмотреть поискав по названию свойства на

-  https://doka.guide/
-  https://developer.mozilla.org/ru/

2024-08-06 19:47 UTC, Avaakum commented on styles/style.css
> +  height: 757px;
**Высоту нужно удалить** Тут она не требуется. Используйте внутренние (padding)   отступы для соответствия макету.
  
  ---
  
  не следует жестко ограничивать высоту блока внутри которого есть какое то содержимое. Размер, количество элементов или количество текста внутри может измениться и при задании фиксированной высоты эти элементы могут "выпасть" из блока, тем самым сломав верстку. 
Поэтому вместо `height` нужно задать такие внутренние отступы (padding) для блока, что бы суммарно с высотой контента блок имел требуемую высоту. 
Это позволит при необходимости адаптироваться блоку по высоте под свое содержимое
Иногда для блоков  без содержимого или для блоков с фоновым изображением может потребоваться так же задание `min-height` которое не позволяет ужиматься блоку меньше определенной высоты даже в том случае если в нем будет мало контента.

2024-08-06 19:47 UTC, Avaakum commented on styles/style.css
> +  width: 240px;
Используйте свойство max-width вместо width что бы при меньшей ширине элемент не занимал больше места

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +      href="./styles/global.css"
---

**Отлично:**

Правильный порядок подключения стилей. Шрифты должны быть подключены первыми, потом общие стили(сброс), потом кастомные. При таком порядке подключении шрифты могут быть использованы в двух последующих файлах.  А так же сброс стилей должен быть до подключения своих стилей из-за специфики CSS, чтобы `global.css` не переопределил никаких наших стилей.

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +        href="#"
---

**Можно лучше:**

Логотип должен быть ссылкой без атрибута href(что бы по ссылке не было перехода)  для улучшения семантики страницы.

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +      <address class="address header__address">
---

**Отлично:**

Отличная семантика

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +            ><span class="ono-letter-2">Н</span
Кроме первой буквы h1 все остальные должны строчными для лучшего восприятия страницы поисковыми машинами. Заглавные должны быть стилизованы через CSS св-во text-transform

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +            ><span class="ono-letter-1">О</span
- `1, 2, first, second и т.д`  порядковые числительные не следует применять  в названиях, т.к. порядок или числовое значение может измениться. **Нужно переименовать все подобные классы** Можно использовать названия например по выравниванию в этом спринте, например  text-align-center и по значению св-ва letter-spacing-extended // letter-spacing-standart // no-letter-spacing

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +          <span class="aligned-text aligned-text_center"
---

**Можно лучше:**

Для выравнивания межбуквенного разрывов использовать правила межбуквенного интервала

Для того что бы буквы разомкнулись по ширине контейнера необходимо воспользоваться правилом горизонтального интервала. Для гибкого совмещения поведения будет круто добавить в проект 2-сущности, всему тексту заголовка установим горизонтальный разрыв в 30px, первая сущность установит интервал в 60px, вторая будет сбрасывать/обнулять горизонтальный интервал.

Буквы с разрывами придётся дополнительно обернуть в <span> и воспользоваться в определённых местах классами с горизонтальными интервалами

1 строка 
* 		Буква о по макету имеет разрыв в 30px
* 		Буквы но по макету имеют разрыв в 60px

2 строка
* 		Буквы те по макету имеют разрыв в 30px
* 		Буквы бе по макету имеют разрыв в 60px

3 строка: 
* 		Более точным решением обернуть последнюю букву в <span> с сбросом межбуквенного разрыва
* 		Буквы н по макету имеют разрыв в 60px
* 		Буквы ад по макету имеют разрыв 30px

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +          <h2 class="cover__description-text">
Это не заголовок, используйте тег p

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +        <h3 class="lots__heading">Лоты</h3>
- Уровень заголовка не соответствует структуре страницы. Это заголовок секции, по структуре будет  h2


---


- Про заголовки и подзаголовки на примере другой страницы с секциями, хэдером, и футером: у нас есть **один заголовок h1 на странице**, в каждой секции есть свой заголовок h2, если там есть другие элементы с заголовками ниже по иерархии, то они будут h3. Если например в секции был бы заголовок h2 и подзаголовок h3, то элементы с заголовками ниже по иерархии в этой же секции были бы уже h4.

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +            <a class="card-link">
---

**Можно лучше:**

Для ссылок нужно задать атрибут href, или они будут неактивны

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +                <h4 class="card__title">
- Уровень заголовка не соответствует структуре страницы. Тут  и далее в секции будут h3 по структуре

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +        <h3 class="about__title">Об аукционе</h3>
- Уровень заголовка не соответствует структуре страницы. Это заголовок секции, по структуре будет  h2



---

**Можно лучше:**

- Желательно объединить правую часть секции в общий контейнер, по смыслу "текстовое описание")
- Для улучшения семантики этого блока можно использовать тег `<article>` 

 - https://developer.mozilla.org/ru/docs/Web/HTML/Element/article

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +          <br />
- тег `<br>`, который в сегодняшних реалиях используется в основном только для переноса строк для адресов и стихов.  Для соответствия брифу(дизайну) можно только ограничивать максимальную ширину текста. Переносы строк могут не совпадать.  **Можно использовать эти теги только для контактной информации в этом проекте, а в остальных местах нужно его удалить.**

2024-08-06 19:47 UTC, Avaakum commented on index.html
> +      <ul class="footer__social-list">
---

**Можно лучше:**

Можно использовать для обертки списка ссылок тег `<nav>`, можно даже без класса, только для семантики.
Этим элементом принято выделять список из ссылок, отвечающий за навигацию по сайту и не только. Добавление этого элемента улучшает восприятие вашей верстки поисковыми машинами, а так же скринридерами. 
Можно использовать несколько тегов `nav` в проекте.

https://doka.guide/html/nav/#alyona-batickaya-sovetuet

2024-08-06 19:47 UTC, Avaakum commented on styles/style.css
> +.bet-button {
https://disk.yandex.ru/i/ZY31QVMOsyMthw кнопка не наследует семейство шрифтов, необходимо задать либо ` font-family:inherit; ` (что бы унаследовала), либо задать само значение ` font-family: Raleway, sans-serif; ` . Или же можно задать для тега button значение наследования семейства шрифтов в файле global

2024-08-06 19:47 UTC, Avaakum commented on styles/style.css
> +.lots__card-list-item {
https://disk.yandex.ru/i/jhjv3Efc5j0UJg Нужно задать минимальную высоту, что бы при добавлении новых карточек они сохраняли высоту из макета

2024-08-06 22:05 UTC, BurovYA commented on index.html
> +        <h3 class="about__title">Об аукционе</h3>
Добрый день. Благодарю за подробное ревью. Хотел написать что валидатор просит и в `<article>` и в `<section>` добавлять тэг заголовка `<h2-6>`. Поэтому я сделаю div, чтобы валидатор не давал предупреждений

![image](https://github.com/user-attachments/assets/63e7cdf6-a1ad-4736-a7eb-401a0aed73f3)

2024-08-07 12:34 UTC, Avaakum commented on index.html
> +        <h3 class="about__title">Об аукционе</h3>
Предупреждения валидатора это ничего страшного, главное, что бы не было критических ошибок. Комментарий "можно лучше", исправление по желанию.

2024-08-07 16:46 UTC, Avaakum approved these changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. Сейчас страничка выглядит прекрасно, всё работает отлично. Отличная семантика и структура. Желаю вам удачи в следующих спринтах и проектах! 

---

_Что необходимо исправить:_

-  комментарий в коде

  
---


Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 


Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)



**БЭМ**

- Соглашение по именованию БЭМ https://ru.bem.info/methodology/naming-convention/
- Часто используемые слова в классах https://github.com/yoksel/common-words
- Где описывать геометрию https://ru.bem.info/methodology/faq/#Зачем-внешнюю-геометрию-и-позиционирование-задавать-через-родительский-блок
- Проверить БЭМ валидатором https://nglazov.github.io/bem-validator-page/

** Доступность**

- https://medium.com/web-standards/what-accessibility-taught-me-207d1ff0e80c



**Игры по flex/grid**

- https://flexboxfroggy.com/#ru
- https://cssgridgarden.com/#ru




**Grid-layout**

- https://css-tricks.com/snippets/css/complete-guide-grid/ (en)
- https://tuhub.ru/posts/css-grid-complete-guide
- https://medium.com/@stasonmars/вёрстка-на-grid-в-css-полное-руководство-и-справочник-220508316f8b

2024-08-07 16:46 UTC, Avaakum commented on styles/style.css
> +.card-link {
Для ссылки нужно добавить `     text-decoration: none; `, что у абзаца в карточке не отображалось лишнее подчёркивание.

2024-08-07 17:59 UTC, merged